
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


import base64
from pathlib import Path
from pydoc import text

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage , END
from cryptography.fernet import Fernet
from datetime import date

from requests import delete

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("650x400")
window.configure(bg = "#FFFFFF")
window.title("AES Encrption app by amirkho.ir")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 400,
    width = 650,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    325.0,
    0.0,
    650.0,
    400.0,
    fill="#8A47DE",
    outline="")

canvas.create_text(
    78.0,
    21.0,
    anchor="nw",
    text="AES Encryption",
    fill="#000000",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    454.0,
    21.0,
    anchor="nw",
    text="Decryption",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    164.0,
    135.5,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#E5E5E5",
    highlightthickness=0,
    fg="black",
    font=("RobotoRoman Medium", 15 * -1),
)
entry_1.place(
    x=58.0,
    y=99.0,
    width=212.0,
    height=71.0
)

canvas.create_text(
    56.0,
    77.0,
    anchor="nw",
    text="source text",
    fill="#686060",
    font=("Inter", 14 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    504.0,
    135.5,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#E5E5E5",
    highlightthickness=0,
    fg="black",
    font=("RobotoRoman Medium", 14 * -1),
    
)
entry_2.place(
    x=398.0,
    y=99.0,
    width=212.0,
    height=71.0
)

canvas.create_text(
    396.0,
    77.0,
    anchor="nw",
    text="chiper text",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    396.0,
    179.0,
    anchor="nw",
    text="key",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    396.0,
    295.0,
    anchor="nw",
    text="clear text",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: enc(),
    relief="flat"
)
button_1.place(
    x=105.0,
    y=201.0,
    width=108.0,
    height=36.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: dec(),
    relief="flat"
)
button_2.place(
    x=466.0,
    y=244.0,
    width=77.0,
    height=28.0
)

canvas.create_text(
    4.0,
    385.0,
    anchor="nw",
    text="amirkho.ir | github.com/amirkho-py",
    fill="#898989",
    font=("Inter", 10 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    504.0,
    216.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#E5E5E5",
    highlightthickness=0,
    fg="black",
    font=("RobotoRoman Medium", 14 * -1),
)
entry_3.place(
    x=398.0,
    y=201.0,
    width=212.0,
    height=29.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    504.0,
    345.5,
    image=entry_image_4
)
entry_4 = Text(
    bd=0,
    bg="#E5E5E5",
    highlightthickness=0,
    fg="black",
    font=("RobotoRoman Medium", 15 * -1),
)
entry_4.place(
    x=398.0,
    y=315.0,
    width=212.0,
    height=59.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    231.0,
    218.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    556.875,
    257.5,
    image=image_image_2
)

def enc():
    key = Fernet.generate_key()
    source = str(entry_1.get("1.0","end-1c"))
    msg = source.encode()
    f = Fernet(key)
    encrypted = f.encrypt(msg)

    with open("data&keys.txt" , mode='a' , encoding="utf-8") as file:
        today = date.today()
        result = "Date: " + str(today) + '\n' + "chiper text: " + encrypted.decode() + '\n' + "key: "+ key.decode() + '\n' + "==========================================="+ '\n'
        file.write(result)


def dec():
    entry_4.delete('1.0', END)
    key = entry_3.get().encode()
    chiper = entry_2.get("1.0","end-1c").encode()
   

    f = Fernet(key)
    decrypted = f.decrypt(chiper)
    entry_4.insert(END, decrypted.decode())


window.resizable(False, False)
window.mainloop()
